language: node_js
node_js:
  - "0.10"
before_install:
  - bundle install
  - ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
  
install:
  - brew install GraphicsMagick
  - brew install phantomjs
  - npm install -g bower
  - npm install
  - bower install

script: "grunt dev" 